### ISSUE TITLE
2010-zone-b paper

### ISSUE THREAD

**Issue by hong-yi** [shrmnk/CO1109-Answers#6]
Question 3a(ii)

Output should be `three`

Question 3a(iii) 

An `ArrayIndexOutOfBoundsException` should be thrown. No output expected.

**Comment by shrmnk** [comment]
I just reviewed the question, and noticed that the main method was not properly defined:
`public static void main(String args) {`

`args` was not defined as a String array - therefore, the output for both 3a(ii) and 3a(iii) should be:

`error: array required, but String found`

---

Otherwise, assuming that it was a typographical error and the main method was properly defined accepting a String array for args, then:

**Question 3a(ii)**
`System.out.println(args[0]);`
Will print the first command-line argument (at index 0).

**Question 3a(iii)**
`System.out.println(args[1]);`
Will print the second command-line argument (at index 1).
